// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mivtqxamouqwbyvrztvi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1pdnRxeGFtb3Vxd2J5dnJ6dHZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MTA1MDEsImV4cCI6MjA3MTE4NjUwMX0.GmgiSqA3dTIDboMj5LZ5VstOYDtKvZbH-qtS52gh8vU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});